In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
%matplotlib inline

from sklearn import tree, ensemble
from sklearn.metrics import accuracy_score, confusion_matrix
from sklearn.metrics import precision_score, recall_score, f1_score

In [3]:
middle = pd.read_csv('./data/middle.csv')

In [4]:
x = middle.iloc[:, :-1].values
y = middle.iloc[:, -1].values

In [6]:
x, x.shape, y, y.shape

(array([[0.2630173 , 0.75943461, 0.47215884, 0.36570879, 0.3311193 ],
        [0.19239765, 0.51414998, 0.22298671, 0.38825704, 0.30784603],
        [0.51399659, 0.44834533, 0.55466555, 0.39488594, 0.36345489],
        [0.38773349, 0.58295612, 0.42599865, 0.3496149 , 0.19745576],
        [0.42167405, 0.56078086, 0.43053578, 0.73441311, 0.35203734],
        [0.23469294, 0.54517782, 0.39570657, 0.48924468, 0.27591993],
        [0.22566019, 0.76835212, 0.41422909, 0.41538373, 0.19211627],
        [0.32739918, 0.80561335, 0.48688103, 0.43682852, 0.30881921],
        [0.31035202, 0.78164678, 0.43463183, 0.2876314 , 0.21364218],
        [0.34484129, 0.94676367, 0.45959479, 0.32362436, 0.22006993],
        [0.27302101, 0.75484889, 0.51226598, 0.28581768, 0.22835091],
        [0.19802664, 0.70836258, 0.47941553, 0.42311828, 0.17910679],
        [0.35324615, 0.44425109, 0.25497355, 0.38722925, 0.29777736],
        [0.20244306, 1.07627031, 0.32900676, 0.23429636, 0.29785087],
        [0.33197247,

In [7]:
# 데이터 정규화

from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()
scaler.fit(x)

StandardScaler()

In [8]:
scaler.transform(x)

array([[-6.79490582e-01,  2.85452572e-01,  7.69363065e-01,
        -3.92848549e-01,  1.16109560e+00],
       [-1.36649081e+00, -7.93115937e-01, -1.70438786e+00,
        -1.77986086e-01,  7.31897271e-01],
       [ 1.76207947e+00, -1.08247293e+00,  1.58847972e+00,
        -1.14819268e-01,  1.75741834e+00],
       [ 5.33770153e-01, -4.90560785e-01,  3.11090235e-01,
        -5.46207407e-01, -1.30388542e+00],
       [ 8.63949841e-01, -5.88070095e-01,  3.56134286e-01,
         3.12053813e+00,  1.54685944e+00],
       [-9.55034863e-01, -6.56679973e-01,  1.03540717e-02,
         7.84325978e-01,  1.43126140e-01],
       [-1.04290710e+00,  3.24664723e-01,  1.94243500e-01,
         8.05043535e-02, -1.40235462e+00],
       [-5.31724583e-02,  4.88510281e-01,  9.15523136e-01,
         2.84851975e-01,  7.49844332e-01],
       [-2.19010248e-01,  3.83124161e-01,  3.96799407e-01,
        -1.13684875e+00, -1.00538045e+00],
       [ 1.16507338e-01,  1.10917815e+00,  6.44628679e-01,
        -7.93871530e-01

In [9]:
x_regu = scaler.transform(x)
x_regu.shape, type(x)

((100, 5), numpy.ndarray)

In [10]:
# 랜덤포레스트 분류기

classifier = ensemble.RandomForestClassifier(n_estimators=20, max_depth=3, criterion='gini')
classifier.fit(x_regu, y)

RandomForestClassifier(max_depth=3, n_estimators=20)

In [11]:
x_regu, type(x_regu),x.shape, y, type(y), y.shape

(array([[-6.79490582e-01,  2.85452572e-01,  7.69363065e-01,
         -3.92848549e-01,  1.16109560e+00],
        [-1.36649081e+00, -7.93115937e-01, -1.70438786e+00,
         -1.77986086e-01,  7.31897271e-01],
        [ 1.76207947e+00, -1.08247293e+00,  1.58847972e+00,
         -1.14819268e-01,  1.75741834e+00],
        [ 5.33770153e-01, -4.90560785e-01,  3.11090235e-01,
         -5.46207407e-01, -1.30388542e+00],
        [ 8.63949841e-01, -5.88070095e-01,  3.56134286e-01,
          3.12053813e+00,  1.54685944e+00],
        [-9.55034863e-01, -6.56679973e-01,  1.03540717e-02,
          7.84325978e-01,  1.43126140e-01],
        [-1.04290710e+00,  3.24664723e-01,  1.94243500e-01,
          8.05043535e-02, -1.40235462e+00],
        [-5.31724583e-02,  4.88510281e-01,  9.15523136e-01,
          2.84851975e-01,  7.49844332e-01],
        [-2.19010248e-01,  3.83124161e-01,  3.96799407e-01,
         -1.13684875e+00, -1.00538045e+00],
        [ 1.16507338e-01,  1.10917815e+00,  6.44628679e-01,
    

In [12]:
# 실제값
expected = y
expected

array([1, 1, 0, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 0, 0,
       1, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 0, 1, 0, 1, 0,
       1, 0, 1, 0, 1, 1, 1, 0, 0, 1, 0, 1, 1, 0, 0, 0, 0, 1, 0, 1, 1, 0,
       1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 0, 1, 0, 1, 1, 1, 1, 1,
       0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 0, 0], dtype=int64)

In [13]:
# 예측값
predicted = classifier.predict(x_regu)
predicted

array([1, 1, 0, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 0,
       1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 0, 1, 0, 1, 1,
       1, 0, 1, 0, 1, 1, 1, 0, 1, 1, 0, 1, 1, 1, 0, 1, 0, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1], dtype=int64)

In [15]:
print('accuracy_score:',accuracy_score(expected, predicted))
print('confusion_matrix:\n',confusion_matrix(expected, predicted))

accuracy_score: 0.86
confusion_matrix:
 [[17 14]
 [ 0 69]]


#### 에이다부스트_AdaBoost

In [16]:
classifier2 = ensemble.AdaBoostClassifier(base_estimator=tree.DecisionTreeClassifier(max_depth=3), n_estimators=20)
# base를 decision tree모델로 설정

In [17]:
classifier2.fit(x_regu, y)

AdaBoostClassifier(base_estimator=DecisionTreeClassifier(max_depth=3),
                   n_estimators=20)

In [18]:
# 분류기 성능 확인

expected2 = y
predicted2 = classifier2.predict(x_regu)

print(predicted2)

[1 1 0 1 0 1 1 1 1 1 1 1 1 1 0 1 1 1 1 1 0 0 1 0 0 0 1 1 1 1 1 1 1 0 0 1 1
 1 1 0 1 0 1 0 1 0 1 0 1 1 1 0 0 1 0 1 1 0 0 0 0 1 0 1 1 0 1 1 1 1 1 1 1 0
 1 1 1 1 1 1 0 1 0 1 1 1 1 1 0 1 1 1 1 0 1 1 1 1 0 0]


In [19]:
print('accuracy_score:',accuracy_score(expected2, predicted2))
print('confusion_matrix:\n',confusion_matrix(expected2, predicted2))

accuracy_score: 1.0
confusion_matrix:
 [[31  0]
 [ 0 69]]
