In [1]:
from keras.models import Sequential
from keras.layers import Dense
from sklearn.model_selection import train_test_split

import numpy as np
import pandas as pd
import tensorflow as tf

In [2]:
# seed 값 설정

seed = 42

np.random.seed(seed)
tf.random.set_seed(seed)

In [4]:
pd.read_csv('/content/drive/MyDrive/Colab Notebooks/02_DeepLearning/dataset/housing.csv', delim_whitespace=True, header=None).head()

0     1     2   3      4      5     6       7   8      9     10  \
0  0.00632  18.0  2.31   0  0.538  6.575  65.2  4.0900   1  296.0  15.3   
1  0.02731   0.0  7.07   0  0.469  6.421  78.9  4.9671   2  242.0  17.8   
2  0.02729   0.0  7.07   0  0.469  7.185  61.1  4.9671   2  242.0  17.8   
3  0.03237   0.0  2.18   0  0.458  6.998  45.8  6.0622   3  222.0  18.7   
4  0.06905   0.0  2.18   0  0.458  7.147  54.2  6.0622   3  222.0  18.7   

       11    12    13  
0  396.90  4.98  24.0  
1  396.90  9.14  21.6  
2  392.83  4.03  34.7  
3  394.63  2.94  33.4  
4  396.90  5.33  36.2

In [5]:
df = pd.read_csv('/content/drive/MyDrive/Colab Notebooks/02_DeepLearning/dataset/housing.csv', delim_whitespace=True, header=None)

In [6]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 506 entries, 0 to 505
Data columns (total 14 columns):
 #   Column  Non-Null Count  Dtype  
---  ------  --------------  -----  
 0   0       506 non-null    float64
 1   1       506 non-null    float64
 2   2       506 non-null    float64
 3   3       506 non-null    int64  
 4   4       506 non-null    float64
 5   5       506 non-null    float64
 6   6       506 non-null    float64
 7   7       506 non-null    float64
 8   8       506 non-null    int64  
 9   9       506 non-null    float64
 10  10      506 non-null    float64
 11  11      506 non-null    float64
 12  12      506 non-null    float64
 13  13      506 non-null    float64
dtypes: float64(12), int64(2)
memory usage: 55.5 KB


In [7]:
df.head()

0     1     2   3      4      5     6       7   8      9     10  \
0  0.00632  18.0  2.31   0  0.538  6.575  65.2  4.0900   1  296.0  15.3   
1  0.02731   0.0  7.07   0  0.469  6.421  78.9  4.9671   2  242.0  17.8   
2  0.02729   0.0  7.07   0  0.469  7.185  61.1  4.9671   2  242.0  17.8   
3  0.03237   0.0  2.18   0  0.458  6.998  45.8  6.0622   3  222.0  18.7   
4  0.06905   0.0  2.18   0  0.458  7.147  54.2  6.0622   3  222.0  18.7   

       11    12    13  
0  396.90  4.98  24.0  
1  396.90  9.14  21.6  
2  392.83  4.03  34.7  
3  394.63  2.94  33.4  
4  396.90  5.33  36.2

In [8]:
df.values

array([[6.3200e-03, 1.8000e+01, 2.3100e+00, ..., 3.9690e+02, 4.9800e+00,
        2.4000e+01],
       [2.7310e-02, 0.0000e+00, 7.0700e+00, ..., 3.9690e+02, 9.1400e+00,
        2.1600e+01],
       [2.7290e-02, 0.0000e+00, 7.0700e+00, ..., 3.9283e+02, 4.0300e+00,
        3.4700e+01],
       ...,
       [6.0760e-02, 0.0000e+00, 1.1930e+01, ..., 3.9690e+02, 5.6400e+00,
        2.3900e+01],
       [1.0959e-01, 0.0000e+00, 1.1930e+01, ..., 3.9345e+02, 6.4800e+00,
        2.2000e+01],
       [4.7410e-02, 0.0000e+00, 1.1930e+01, ..., 3.9690e+02, 7.8800e+00,
        1.1900e+01]])

In [9]:
dataset = df.values

x = dataset[:, :-1]
y = dataset[:, -1]

In [10]:
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.3, random_state=seed)

In [12]:
# 모델 생성

model = Sequential()
model.add(Dense(30, input_dim=13, activation='relu'))
model.add(Dense(6, activation='relu'))
model.add(Dense(1))  # 활성화 함수 없음 (회귀 : 예측)

In [16]:
# 환경설정

model.compile(loss='mean_squared_error',
              optimizer='adam')

In [17]:
# 모델 학습

model.fit(x_train, y_train, epochs=200, batch_size=10)

Epoch 1/200
36/36 [==============================] - 3s 4ms/step - loss: 234.0912
Epoch 2/200
36/36 [==============================] - 0s 3ms/step - loss: 87.7962
Epoch 3/200
36/36 [==============================] - 0s 3ms/step - loss: 76.9846
Epoch 4/200
36/36 [==============================] - 0s 3ms/step - loss: 73.5665
Epoch 5/200
36/36 [==============================] - 0s 3ms/step - loss: 72.2700
Epoch 6/200
36/36 [==============================] - 0s 3ms/step - loss: 68.5672
Epoch 7/200
36/36 [==============================] - 0s 3ms/step - loss: 69.2924
Epoch 8/200
36/36 [==============================] - 0s 4ms/step - loss: 65.4548
Epoch 9/200
36/36 [==============================] - 0s 3ms/step - loss: 69.9111
Epoch 10/200
36/36 [==============================] - 0s 4ms/step - loss: 63.1985
Epoch 11/200
36/36 [==============================] - 0s 4ms/step - loss: 63.7398
Epoch 12/200
36/36 [==============================] - 0s 4ms/step - loss: 62.5730
Epoch 13/200
36/36 [====

In [18]:
# 예측값과 실제값 비교

model.predict(x_test)

array([[27.863834 ],
       [38.15018  ],
       [18.040918 ],
       [29.091303 ],
       [16.363546 ],
       [19.121708 ],
       [17.449718 ],
       [17.938972 ],
       [19.388577 ],
       [20.86662  ],
       [19.106161 ],
       [18.445473 ],
       [ 2.7235608],
       [19.555899 ],
       [20.08457  ],
       [22.669144 ],
       [21.222713 ],
       [10.734869 ],
       [43.75916  ],
       [15.753111 ],
       [31.256824 ],
       [31.606724 ],
       [15.725173 ],
       [22.887756 ],
       [16.631647 ],
       [14.825735 ],
       [24.619453 ],
       [14.672462 ],
       [18.275522 ],
       [20.737486 ],
       [20.956724 ],
       [28.274345 ],
       [22.641998 ],
       [27.104229 ],
       [14.905336 ],
       [15.064413 ],
       [29.90437  ],
       [25.53042  ],
       [20.548355 ],
       [26.130411 ],
       [17.68478  ],
       [34.914707 ],
       [48.200275 ],
       [19.734203 ],
       [27.104328 ],
       [16.214832 ],
       [16.625002 ],
       [27.86

In [19]:
model.predict(x_test).flatten()

array([27.863834 , 38.15018  , 18.040918 , 29.091303 , 16.363546 ,
       19.121708 , 17.449718 , 17.938972 , 19.388577 , 20.86662  ,
       19.106161 , 18.445473 ,  2.7235608, 19.555899 , 20.08457  ,
       22.669144 , 21.222713 , 10.734869 , 43.75916  , 15.753111 ,
       31.256824 , 31.606724 , 15.725173 , 22.887756 , 16.631647 ,
       14.825735 , 24.619453 , 14.672462 , 18.275522 , 20.737486 ,
       20.956724 , 28.274345 , 22.641998 , 27.104229 , 14.905336 ,
       15.064413 , 29.90437  , 25.53042  , 20.548355 , 26.130411 ,
       17.68478  , 34.914707 , 48.200275 , 19.734203 , 27.104328 ,
       16.214832 , 16.625002 , 27.86844  , 16.608286 , 32.22019  ,
       19.903252 , 35.00249  , 17.784018 , 27.633333 , 39.541775 ,
       22.71138  , 16.960573 , 37.505894 , 25.963327 , 17.750738 ,
       25.069094 , 32.977604 , 35.481583 , 13.492815 , 23.00951  ,
       17.222906 , 16.187916 , 29.535717 , 34.222916 , 13.706776 ,
       21.237675 , 27.24664  , 12.830893 , 22.346657 , 22.9699

In [20]:
y_test # 실제값

array([23.6, 32.4, 13.6, 22.8, 16.1, 20. , 17.8, 14. , 19.6, 16.8, 21.5,
       18.9,  7. , 21.2, 18.5, 29.8, 18.8, 10.2, 50. , 14.1, 25.2, 29.1,
       12.7, 22.4, 14.2, 13.8, 20.3, 14.9, 21.7, 18.3, 23.1, 23.8, 15. ,
       20.8, 19.1, 19.4, 34.7, 19.5, 24.4, 23.4, 19.7, 28.2, 50. , 17.4,
       22.6, 15.1, 13.1, 24.2, 19.9, 24. , 18.9, 35.4, 15.2, 26.5, 43.5,
       21.2, 18.4, 28.5, 23.9, 18.5, 25. , 35.4, 31.5, 20.2, 24.1, 20. ,
       13.1, 24.8, 30.8, 12.7, 20. , 23.7, 10.8, 20.6, 20.8,  5. , 20.1,
       48.5, 10.9,  7. , 20.9, 17.2, 20.9,  9.7, 19.4, 29. , 16.4, 25. ,
       25. , 17.1, 23.2, 10.4, 19.6, 17.2, 27.5, 23. , 50. , 17.9,  9.6,
       17.2, 22.5, 21.4, 12. , 19.9, 19.4, 13.4, 18.2, 24.6, 21.1, 24.7,
        8.7, 27.5, 20.7, 36.2, 31.6, 11.7, 39.8, 13.9, 21.8, 23.7, 17.6,
       24.4,  8.8, 19.2, 25.3, 20.4, 23.1, 37.9, 15.6, 45.4, 15.7, 22.6,
       14.5, 18.7, 17.8, 16.1, 20.6, 31.6, 29.1, 15.6, 17.5, 22.5, 19.4,
       19.3,  8.5, 20.6, 17. , 17.1, 14.5, 50. , 14

In [21]:
y_pred = model.predict(x_test).flatten()   # 예측값

for i in range(10):
    label = y_test[i]
    prediction = y_pred[i]
    print('실제 가격: {:.3f}, 예상가격: {:.3f}'.format(label, prediction))

실제 가격: 23.600, 예상가격: 27.864
실제 가격: 32.400, 예상가격: 38.150
실제 가격: 13.600, 예상가격: 18.041
실제 가격: 22.800, 예상가격: 29.091
실제 가격: 16.100, 예상가격: 16.364
실제 가격: 20.000, 예상가격: 19.122
실제 가격: 17.800, 예상가격: 17.450
실제 가격: 14.000, 예상가격: 17.939
실제 가격: 19.600, 예상가격: 19.389
실제 가격: 16.800, 예상가격: 20.867
