In [1]:
# 심봤다 테스트

from keras.models import Sequential
from keras.layers.core import Dense
from sklearn.preprocessing import LabelEncoder

import pandas as pd
import numpy as np 
import tensorflow as tf

# seed값 설정
np.random.seed(42)
tf.random.set_seed(42)

In [2]:
from google.colab import drive
drive.mount('/content/drive/')

Drive already mounted at /content/drive/; to attempt to forcibly remount, call drive.mount("/content/drive/", force_remount=True).


In [3]:
# 데이터 입력

df = pd.read_csv('/content/drive/MyDrive/Colab Notebooks/02_DeepLearning/dataset/sonar.csv', header=None)

In [4]:
# 데이터 개괄적 살펴보기
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 208 entries, 0 to 207
Data columns (total 61 columns):
 #   Column  Non-Null Count  Dtype  
---  ------  --------------  -----  
 0   0       208 non-null    float64
 1   1       208 non-null    float64
 2   2       208 non-null    float64
 3   3       208 non-null    float64
 4   4       208 non-null    float64
 5   5       208 non-null    float64
 6   6       208 non-null    float64
 7   7       208 non-null    float64
 8   8       208 non-null    float64
 9   9       208 non-null    float64
 10  10      208 non-null    float64
 11  11      208 non-null    float64
 12  12      208 non-null    float64
 13  13      208 non-null    float64
 14  14      208 non-null    float64
 15  15      208 non-null    float64
 16  16      208 non-null    float64
 17  17      208 non-null    float64
 18  18      208 non-null    float64
 19  19      208 non-null    float64
 20  20      208 non-null    float64
 21  21      208 non-null    float64
 22  22

In [5]:
df.values

array([[0.02, 0.0371, 0.0428, ..., 0.009, 0.0032, 'R'],
       [0.0453, 0.0523, 0.0843, ..., 0.0052, 0.0044, 'R'],
       [0.0262, 0.0582, 0.1099, ..., 0.0095, 0.0078, 'R'],
       ...,
       [0.0522, 0.0437, 0.018, ..., 0.0077, 0.0031, 'M'],
       [0.0303, 0.0353, 0.049, ..., 0.0036, 0.0048, 'M'],
       [0.026, 0.0363, 0.0136, ..., 0.0061, 0.0115, 'M']], dtype=object)

In [6]:
dataset = df.values

# x = dataset[:, :-1]
# y_obj = dataset[:, -1]

# ValueError: Failed to convert a NumPy array to a Tensor (Unsupported object type float). 해결방안
x = np.asarray(dataset[:, :-1]).astype(np.float32)
y_obj = dataset[:, -1]

In [7]:
x, y_obj

(array([[0.02  , 0.0371, 0.0428, ..., 0.0084, 0.009 , 0.0032],
        [0.0453, 0.0523, 0.0843, ..., 0.0049, 0.0052, 0.0044],
        [0.0262, 0.0582, 0.1099, ..., 0.0164, 0.0095, 0.0078],
        ...,
        [0.0522, 0.0437, 0.018 , ..., 0.0138, 0.0077, 0.0031],
        [0.0303, 0.0353, 0.049 , ..., 0.0079, 0.0036, 0.0048],
        [0.026 , 0.0363, 0.0136, ..., 0.0036, 0.0061, 0.0115]],
       dtype=float32),
 array(['R', 'R', 'R', 'R', 'R', 'R', 'R', 'R', 'R', 'R', 'R', 'R', 'R',
        'R', 'R', 'R', 'R', 'R', 'R', 'R', 'R', 'R', 'R', 'R', 'R', 'R',
        'R', 'R', 'R', 'R', 'R', 'R', 'R', 'R', 'R', 'R', 'R', 'R', 'R',
        'R', 'R', 'R', 'R', 'R', 'R', 'R', 'R', 'R', 'R', 'R', 'R', 'R',
        'R', 'R', 'R', 'R', 'R', 'R', 'R', 'R', 'R', 'R', 'R', 'R', 'R',
        'R', 'R', 'R', 'R', 'R', 'R', 'R', 'R', 'R', 'R', 'R', 'R', 'R',
        'R', 'R', 'R', 'R', 'R', 'R', 'R', 'R', 'R', 'R', 'R', 'R', 'R',
        'R', 'R', 'R', 'R', 'R', 'R', 'M', 'M', 'M', 'M', 'M', 'M', 'M',
 

In [8]:
# 문자열 변환

le = LabelEncoder()
le.fit(y_obj)
y_encoded = le.transform(y_obj)

In [9]:
y_encoded

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [10]:
# 학습 셋과 테스트 셋 구분(train_test_split())

from sklearn.model_selection import train_test_split

x_train, x_test, y_train, y_test = train_test_split(x, y_encoded, test_size=0.3, random_state=42)

In [11]:
# 모델 설정 (모델 형태 구성)

model = Sequential()
model.add(Dense(24, input_dim=60, activation='relu'))
model.add(Dense(10, activation='relu'))
model.add(Dense(1, activation='sigmoid')) # 이진분류 : 시그모이드 함수 사용

In [12]:
# 모델 컴파일 (모델 환결성정)

model.compile(loss='mean_squared_error',      # 오차함수 : mse
              optimizer = 'adam',
              metrics=['accuracy'])

In [13]:
# 모델 실행 (fit)

# model.fit(x,y_encoded, epochs=120, batch_size=5)
model.fit(x_train,y_train, epochs=120, batch_size=5)

Epoch 1/120
29/29 [==============================] - 2s 5ms/step - loss: 0.2398 - accuracy: 0.5241
Epoch 2/120
29/29 [==============================] - 0s 4ms/step - loss: 0.2269 - accuracy: 0.5310
Epoch 3/120
29/29 [==============================] - 0s 5ms/step - loss: 0.2228 - accuracy: 0.6414
Epoch 4/120
29/29 [==============================] - 0s 4ms/step - loss: 0.2187 - accuracy: 0.6552
Epoch 5/120
29/29 [==============================] - 0s 4ms/step - loss: 0.2141 - accuracy: 0.6621
Epoch 6/120
29/29 [==============================] - 0s 3ms/step - loss: 0.2097 - accuracy: 0.6897
Epoch 7/120
29/29 [==============================] - 0s 3ms/step - loss: 0.2053 - accuracy: 0.7310
Epoch 8/120
29/29 [==============================] - 0s 4ms/step - loss: 0.2007 - accuracy: 0.7241
Epoch 9/120
29/29 [==============================] - 0s 3ms/step - loss: 0.1969 - accuracy: 0.7931
Epoch 10/120
29/29 [==============================] - 0s 4ms/step - loss: 0.1933 - accuracy: 0.7103
Epoch 11/

In [14]:
# 결과 출력 및 평가

model.evaluate(x_test,y_test)

2/2 [==============================] - 0s 5ms/step - loss: 0.1116 - accuracy: 0.8571


[0.11156462877988815, 0.8571428656578064]

In [15]:
print('\n test_Accuracy: %.4f'%(model.evaluate(x_test, y_test)[1]))

2/2 [==============================] - 0s 5ms/step - loss: 0.1116 - accuracy: 0.8571

 test_Accuracy: 0.8571


In [16]:
model.save('/content/drive/MyDrive/Colab Notebooks/02_DeepLearning/model/sonar_model.h5') # 모델 저장

In [19]:
del model

In [22]:
from keras.models import load_model

model = load_model('/content/drive/MyDrive/Colab Notebooks/02_DeepLearning/model/sonar_model.h5')  # 모델 재사용

In [23]:
print('\n test_Accuracy: %.4f'%(model.evaluate(x_test, y_test)[1]))

2/2 [==============================] - 0s 6ms/step - loss: 0.1116 - accuracy: 0.8571

 test_Accuracy: 0.8571
