In [1]:
# 심봤다 테스트

from keras.models import Sequential
from keras.layers.core import Dense
from sklearn.preprocessing import LabelEncoder
from sklearn.model_selection import StratifiedKFold

import pandas as pd
import numpy as np 
import tensorflow as tf

# seed값 설정
np.random.seed(42)
tf.random.set_seed(42)

In [2]:
from google.colab import drive
drive.mount('/content/drive/')

Drive already mounted at /content/drive/; to attempt to forcibly remount, call drive.mount("/content/drive/", force_remount=True).


In [3]:
# 데이터 입력

df = pd.read_csv('/content/drive/MyDrive/Colab Notebooks/02_DeepLearning/dataset/sonar.csv', header=None)

In [4]:
# 데이터 개괄적 살펴보기
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 208 entries, 0 to 207
Data columns (total 61 columns):
 #   Column  Non-Null Count  Dtype  
---  ------  --------------  -----  
 0   0       208 non-null    float64
 1   1       208 non-null    float64
 2   2       208 non-null    float64
 3   3       208 non-null    float64
 4   4       208 non-null    float64
 5   5       208 non-null    float64
 6   6       208 non-null    float64
 7   7       208 non-null    float64
 8   8       208 non-null    float64
 9   9       208 non-null    float64
 10  10      208 non-null    float64
 11  11      208 non-null    float64
 12  12      208 non-null    float64
 13  13      208 non-null    float64
 14  14      208 non-null    float64
 15  15      208 non-null    float64
 16  16      208 non-null    float64
 17  17      208 non-null    float64
 18  18      208 non-null    float64
 19  19      208 non-null    float64
 20  20      208 non-null    float64
 21  21      208 non-null    float64
 22  22

In [5]:
df.values

array([[0.02, 0.0371, 0.0428, ..., 0.009, 0.0032, 'R'],
       [0.0453, 0.0523, 0.0843, ..., 0.0052, 0.0044, 'R'],
       [0.0262, 0.0582, 0.1099, ..., 0.0095, 0.0078, 'R'],
       ...,
       [0.0522, 0.0437, 0.018, ..., 0.0077, 0.0031, 'M'],
       [0.0303, 0.0353, 0.049, ..., 0.0036, 0.0048, 'M'],
       [0.026, 0.0363, 0.0136, ..., 0.0061, 0.0115, 'M']], dtype=object)

In [6]:
dataset = df.values

# x = dataset[:, :-1]
# y_obj = dataset[:, -1]

# ValueError: Failed to convert a NumPy array to a Tensor (Unsupported object type float). 해결방안
x = np.asarray(dataset[:, :-1]).astype(np.float32)
y_obj = dataset[:, -1]

In [7]:
x, y_obj

(array([[0.02  , 0.0371, 0.0428, ..., 0.0084, 0.009 , 0.0032],
        [0.0453, 0.0523, 0.0843, ..., 0.0049, 0.0052, 0.0044],
        [0.0262, 0.0582, 0.1099, ..., 0.0164, 0.0095, 0.0078],
        ...,
        [0.0522, 0.0437, 0.018 , ..., 0.0138, 0.0077, 0.0031],
        [0.0303, 0.0353, 0.049 , ..., 0.0079, 0.0036, 0.0048],
        [0.026 , 0.0363, 0.0136, ..., 0.0036, 0.0061, 0.0115]],
       dtype=float32),
 array(['R', 'R', 'R', 'R', 'R', 'R', 'R', 'R', 'R', 'R', 'R', 'R', 'R',
        'R', 'R', 'R', 'R', 'R', 'R', 'R', 'R', 'R', 'R', 'R', 'R', 'R',
        'R', 'R', 'R', 'R', 'R', 'R', 'R', 'R', 'R', 'R', 'R', 'R', 'R',
        'R', 'R', 'R', 'R', 'R', 'R', 'R', 'R', 'R', 'R', 'R', 'R', 'R',
        'R', 'R', 'R', 'R', 'R', 'R', 'R', 'R', 'R', 'R', 'R', 'R', 'R',
        'R', 'R', 'R', 'R', 'R', 'R', 'R', 'R', 'R', 'R', 'R', 'R', 'R',
        'R', 'R', 'R', 'R', 'R', 'R', 'R', 'R', 'R', 'R', 'R', 'R', 'R',
        'R', 'R', 'R', 'R', 'R', 'R', 'M', 'M', 'M', 'M', 'M', 'M', 'M',
 

In [7]:
# 문자열 변환

le = LabelEncoder()
le.fit(y_obj)
y_encoded = le.transform(y_obj)

In [9]:
y_encoded

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [9]:
# 10개의 파일로 쪼갬

n_fold = 10
seed = 42

skf = StratifiedKFold(n_splits=n_fold, shuffle=True, random_state=seed)

In [12]:
accuracy = []

# 모델 설정, 컴파일, 실행

for train, test in skf.split(x,y_encoded):
    model = Sequential()
    model.add(Dense(24, input_dim=60, activation='relu'))
    model.add(Dense(10, activation='relu'))
    model.add(Dense(1, activation='sigmoid'))

    model.compile(loss='mean_squared_error',
                  optimizer='adam',
                  metrics=['accuracy'])
    
    model.fit(x[train], y_encoded[train], epochs=100, batch_size=5)
    k_acc = '%.4f'%(model.evaluate(x[test],y_encoded[test])[1])
    accuracy.append(k_acc)

Epoch 1/100
38/38 [==============================] - 2s 6ms/step - loss: 0.2366 - accuracy: 0.5348
Epoch 2/100
38/38 [==============================] - 0s 5ms/step - loss: 0.2258 - accuracy: 0.5455
Epoch 3/100
38/38 [==============================] - 0s 6ms/step - loss: 0.2209 - accuracy: 0.5775
Epoch 4/100
38/38 [==============================] - 0s 5ms/step - loss: 0.2154 - accuracy: 0.6791
Epoch 5/100
38/38 [==============================] - 0s 6ms/step - loss: 0.2094 - accuracy: 0.6738
Epoch 6/100
38/38 [==============================] - 0s 6ms/step - loss: 0.2053 - accuracy: 0.7166
Epoch 7/100
38/38 [==============================] - 0s 7ms/step - loss: 0.1963 - accuracy: 0.7005
Epoch 8/100
38/38 [==============================] - 0s 6ms/step - loss: 0.1896 - accuracy: 0.7968
Epoch 9/100
38/38 [==============================] - 0s 5ms/step - loss: 0.1827 - accuracy: 0.7487
Epoch 10/100
38/38 [==============================] - 0s 6ms/step - loss: 0.1749 - accuracy: 0.7968
Epoch 11/

In [14]:
# 결과 출력

print('\n %.2f\n fold accuracy: '%n_fold, accuracy)


 10.00
 fold accuracy:  ['0.9524', '0.6667', '0.7619', '0.9524', '0.7143', '0.9048', '0.7143', '0.8571', '0.7500', '0.8500']


In [15]:
accuracy = []

# 모델 설정, 컴파일, 실행

for train, test in skf.split(x,y_encoded):
    model = Sequential()
    model.add(Dense(24, input_dim=60, activation='relu'))
    model.add(Dense(10, activation='relu'))
    model.add(Dense(1, activation='sigmoid'))

    model.compile(loss='binary_crossentropy',
                  optimizer='adam',
                  metrics=['accuracy'])
    
    model.fit(x[train], y_encoded[train], epochs=100, batch_size=5)
    k_acc = '%.4f'%(model.evaluate(x[test],y_encoded[test])[1])
    accuracy.append(k_acc)

Epoch 1/100
38/38 [==============================] - 2s 4ms/step - loss: 0.7208 - accuracy: 0.4652
Epoch 2/100
38/38 [==============================] - 0s 4ms/step - loss: 0.6821 - accuracy: 0.5989
Epoch 3/100
38/38 [==============================] - 0s 4ms/step - loss: 0.6745 - accuracy: 0.6791
Epoch 4/100
38/38 [==============================] - 0s 4ms/step - loss: 0.6609 - accuracy: 0.6738
Epoch 5/100
38/38 [==============================] - 0s 3ms/step - loss: 0.6446 - accuracy: 0.6898
Epoch 6/100
38/38 [==============================] - 0s 4ms/step - loss: 0.6296 - accuracy: 0.7219
Epoch 7/100
38/38 [==============================] - 0s 4ms/step - loss: 0.6049 - accuracy: 0.7540
Epoch 8/100
38/38 [==============================] - 0s 4ms/step - loss: 0.5893 - accuracy: 0.7647
Epoch 9/100
38/38 [==============================] - 0s 4ms/step - loss: 0.5631 - accuracy: 0.7540
Epoch 10/100
38/38 [==============================] - 0s 4ms/step - loss: 0.5471 - accuracy: 0.7487
Epoch 11/

In [16]:
# 결과 출력

print('\n %.2f\n fold accuracy: '%n_fold, accuracy)


 10.00
 fold accuracy:  ['0.9524', '0.7143', '0.7143', '0.9524', '0.6667', '0.8095', '0.8571', '0.9048', '0.7500', '0.8500']
